Altair utils to make graphs brand compliant and to save graphs
nestauk/ai_genomics pull request #114
Opened 2022-09-23 12:39 UTC by india-kerle

from @beingkk 's have-a-go altair demo

2022-09-27 11:06 UTC, Juan-Mateos requested changes
Thanks for adding this!

The code broadly runs although I have suggested a couple of changes to give the user a bit more control over the size of labels and titles in their plot, and to ensure we save figures in the right place.

2022-09-27 11:06 UTC, Juan-Mateos commented on ai_genomics/utils/plotting.py
> +FONTSIZE_NORMAL = 13
I would turn these into parameters in the `configure_plots` function so the user has some control over the size of labels and titles in their chart.

2022-09-27 11:06 UTC, Juan-Mateos commented on ai_genomics/utils/plotting.py
> +FONT = "Averta Demo"  # should be changed depending on what your font is called in your system's font book
This didn't work for me. I had to change it to `Averta`

2022-09-27 11:06 UTC, Juan-Mateos commented on ai_genomics/utils/plotting.py
> +def configure_plots(fig, chart_title: str = "", chart_subtitle: str = ""):
Suggestion: add fontsize parameters with sensible default values e.g. those above

2022-09-27 11:06 UTC, Juan-Mateos commented on ai_genomics/utils/save_plotting.py
> +FIGURE_PATH = Path("outputs/")
This saves the files to a new `outputs` folder in the directory where we are running the script. What about...

```
from ai_genomics import PROJECT_DIR

etc.

FIGURE_PATH = Path(f"{PROJECT_DIR}/outputs/figures")
```

2022-09-28 10:46 UTC, india-kerle commented on ai_genomics/utils/plotting.py
> +FONTSIZE_NORMAL = 13
good idea

2022-09-28 10:49 UTC, india-kerle commented
@Juan-Mateos thanks for your comments - I've made your suggested changes. Let me know if its ok to merge as a result.

2022-09-28 11:26 UTC, Juan-Mateos commented
Looks good, thank you! Merged!

2022-09-28 11:26 UTC, merged