[80] Identify AI genomics people & orgs
nestauk/ai_genomics pull request #82
Opened 2022-08-30 11:03 UTC by Jack-0-0

Closes #80.

---

Checklist:

- [ ] I have refactored my code out from `notebooks/`
- [ ] I have checked the code runs
- [ ] I have tested the code
- [ ] I have run `pre-commit` and addressed any issues not automatically fixed
- [ ] I have merged any new changes from `dev`
- [ ] I have documented the code
  - [ ] Major functions have docstrings
  - [ ] Appropriate information has been added to `README`s
- [ ] I have explained the feature in this PR or (better) in `output/reports/`
- [ ] I have requested a code review

2022-08-30 16:36 UTC, india-kerle requested changes
great! thanks for this jack - the only issue that would need a fix is that you should split entities by camel case in the assignees column for the patent data first as there looks like there are multiple entities per assignee that are not nicely split - then I'd count.

2022-08-30 16:36 UTC, india-kerle commented on ai_genomics/analysis/ai_genomics_experts/patent_assignees.py
> +    )
I think you can just use ast.literal_eval to convert these string values into a list:

```suggestion
    patents["assignee"] =  patents['assignee'].apply(lambda x: ast.literal_eval(x))
```

2022-08-30 16:36 UTC, india-kerle commented on ai_genomics/analysis/ai_genomics_experts/patent_assignees.py
> +
```suggestion
import ast
```

2022-08-30 16:36 UTC, india-kerle commented on ai_genomics/analysis/ai_genomics_experts/patent_assignees.py
> +    )
although this won't work if its an NA, so I'd drop any nans in the assignee col

2022-08-30 16:36 UTC, india-kerle commented on ai_genomics/analysis/ai_genomics_experts/patent_assignees.py
> +        .dropna(subset=["assignee"])
oh nice

2022-08-30 16:36 UTC, india-kerle commented on ai_genomics/analysis/ai_genomics_experts/gtr_people.py
> +    """Add new column combining first name and surnam, select relevant columns"""
```suggestion
    """Add new column combining first name and surname, select relevant columns"""
```

2022-08-30 16:36 UTC, india-kerle commented on ai_genomics/analysis/ai_genomics_experts/patent_assignees.py
> +    top_20_most_assigned_ai_genomics_patents.to_csv(
hmmmm I took a look at the assignee outputs and annoyingly, they can include both the org/institution and name which means that taking a simple count might not be representative. For example, there's a 'The Chinese University Of Hong Kong' assignee but also a 'The Chinese University Of Hong KongYuk Ming Dennis LoKwan Chee ChanWai Kwun Rossa ChiuCharles CantorSequenom, Inc.'. However, these would be counted differently. 

it looks like you can split these assignees based on a camelcase pattern i.e. split 'The Chinese University Of Hong KongGrail, Inc.', at KongGrail.

2022-08-30 16:36 UTC, india-kerle commented on ai_genomics/analysis/ai_genomics_experts/patent_assignees.py
> +    top_20_most_assigned_ai_genomics_patents.to_csv(
for ojd_daps_skills, we have a function to detect camel case - you can modify this function to split assignees based on camel case and then explode assignees then count?

2022-08-30 16:36 UTC, india-kerle commented on ai_genomics/analysis/ai_genomics_experts/patent_assignees.py
> +    top_20_most_assigned_ai_genomics_patents.to_csv(
For reference:

```
def detect_camelcase(text):
    """
    Splits a word written in camel-case into separate sentences. This fixes a case
    when the last word of a sentence in not seperated from the capitalised word of
    the next sentence. This tends to occur with enumerations.
    For example, the string "skillsBe" will be converted to "skills. Be"
    Some camelcases are allowed though - these are found and replaced. e.g. JavaScript
    Note that the present solution doesn't catch all such cases (e.g. "UKSkills")
    Reference: https://stackoverflow.com/questions/1097901/regular-expression-split-string-by-capital-letter-but-ignore-tla
    """
    text = compiled_missing_space_pattern.sub(r"\1. \2\3", text)
    for exception in exception_camelcases:
        exception_cleaned = compiled_missing_space_pattern.sub(r"\1. \2\3", exception)
        if exception_cleaned in text:
            text = text.replace(exception_cleaned, exception)

    return text
```

2022-08-30 16:36 UTC, india-kerle commented on ai_genomics/analysis/ai_genomics_experts/README.md
> +We have used the AI and genomics patents dataset to identify the assignees who are related to the most patent publication numbers.
```suggestion
We have used the AI and genomics patents dataset to identify the top 20 assignees who are related to the most patent publications. 
```

2022-08-30 16:36 UTC, india-kerle commented on ai_genomics/analysis/ai_genomics_experts/README.md
> +# AI Genomics expert people and organisations
actually - could be good to add the numbers of people/orgs per dataset in the readme?

2022-08-30 16:36 UTC, india-kerle commented on ai_genomics/analysis/ai_genomics_experts/cb_orgs_and_people.py
> +    return cb_people.query(f"org_id in {cb_org_ids}").reset_index(drop=True)
oh nice - i always do .str.contains instead of .query but this looks nicer!

2022-08-30 16:36 UTC, india-kerle commented on ai_genomics/analysis/ai_genomics_experts/cb_orgs_and_people.py
> +if __name__ == "__main__":
I checked the outputs and looks like there isn't the same problem as there is with patent assignees - looks good!

2022-08-31 07:38 UTC, Jack-0-0 commented on ai_genomics/analysis/ai_genomics_experts/patent_assignees.py
> +    )
`ast.literal_eval` doesn't work underfortunately.

For example if we have this string: `"['The Procter & Gamble Company' 'Rui Li' 'Shi Huang' 'Tao He' 'Jiquan Liu'\n 'Jian Xu']"`

with `ast.literal_eval` it becomes `['The Procter & Gamble CompanyRui LiShi HuangTao HeJiquan LiuJian Xu']`

and with my function it becomes `['The Procter & Gamble Company',
 'Rui Li',
 'Shi Huang',
 'Tao He',
 'Jiquan Liu',
 'Jian Xu']`

2022-08-31 08:22 UTC, india-kerle commented on ai_genomics/analysis/ai_genomics_experts/patent_assignees.py
> +    )
omg this is why!!!!

2022-08-31 08:22 UTC, india-kerle commented on ai_genomics/analysis/ai_genomics_experts/patent_assignees.py
> +    top_20_most_assigned_ai_genomics_patents.to_csv(
ignore me!! @Jack-0-0

2022-08-31 10:12 UTC, Jack-0-0 commented
Hi @india-kerle, thanks for the review. I've made the changes you suggested and left the `assignee_string_to_list` function as it was.

I also have added a function `replace_sq_brackets_and_dbl_quotes` to clean some of the records that were a list within a string (e.g `'["Myriad Womens Health, Inc."]'`)

2022-08-31 10:55 UTC, india-kerle reviewed
thanks for addressing the comments! looks good.

2022-08-31 10:55 UTC, india-kerle commented on ai_genomics/getters/gtr.py
> +def get_gtr_from_s3(entity_type: str) -> pd.DataFrame:
nice

2022-08-31 11:17 UTC, merged